services:
    davidiq.mailinglist.listener:
        class: davidiq\mailinglist\event\listener
        arguments:
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
